# Generated by Django 4.2 on 2023-04-19 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesfield',
            name='photo',
            field=models.ImageField(blank=True, default='images/default/default.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='imagesfield',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
